create table if not exists public.aquarium_events (
  id bigint generated by default as identity primary key,
  tank_id text not null check (char_length(tank_id) between 20 and 64),
  action text not null check (action in ('feed', 'water', 'parameters', 'filter1', 'filter2', 'fertilizer')),
  details jsonb not null default '{}'::jsonb,
  created_at bigint not null
);

create index if not exists aquarium_events_tank_created_idx
  on public.aquarium_events (tank_id, created_at desc);

alter table public.aquarium_events enable row level security;

-- No se crean políticas públicas. La aplicación accede desde el servidor de
-- Vercel mediante la clave service_role, que nunca se envía al navegador.
